"""add username, approval_status, theme, language, subcategory, report student link

Revision ID: 06b9c387e4c0
Revises: e8deb16ac183
Create Date: 2026-07-13 17:45:54.574448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b9c387e4c0'
down_revision = 'e8deb16ac183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory', sa.String(length=100), nullable=True))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reports_student_id_users', 'users', ['student_id'], ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='approval_status'), nullable=False, server_default='approved'))
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=10), nullable=False, server_default='light'))
        batch_op.add_column(sa.Column('language_preference', sa.String(length=10), nullable=False, server_default='en'))
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_column('language_preference')
        batch_op.drop_column('theme_preference')
        batch_op.drop_column('approval_status')
        batch_op.drop_column('username')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reports_student_id_users', type_='foreignkey')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('subcategory')

    # ### end Alembic commands ###
