"""initial schema

Revision ID: e48c4a850b90
Revises: 
Create Date: 2026-08-13 07:27:38.661308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48c4a850b90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('publisher', sa.String(length=150), nullable=True),
    sa.Column('year_published', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_physical_copies', sa.Integer(), nullable=False),
    sa.Column('available_physical_copies', sa.Integer(), nullable=False),
    sa.Column('has_digital', sa.Boolean(), nullable=False),
    sa.Column('digital_file_path', sa.String(length=500), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('isbn')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('ix_books_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_category'), ['category'], unique=False)
        batch_op.create_index('ix_books_category_active', ['category', 'is_active'], unique=False)

    op.create_table('system_settings',
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('setting_key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'librarian', 'admin', name='user_role'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('year_of_study', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='approval_status'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('theme_preference', sa.String(length=10), nullable=False),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_approval_status', ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_role_active', ['role', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_student_id'), ['student_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_created', ['action_type', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_created', ['created_at'], unique=False)

    op.create_table('checkouts',
    sa.Column('checkout_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('librarian_id', sa.Integer(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('expected_return_date', sa.Date(), nullable=False),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'returned', 'overdue', name='checkout_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['librarian_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('checkout_id')
    )
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.create_index('ix_checkouts_book', ['book_id'], unique=False)
        batch_op.create_index('ix_checkouts_status_expected', ['status', 'expected_return_date'], unique=False)
        batch_op.create_index('ix_checkouts_user_status', ['user_id', 'status'], unique=False)

    op.create_table('library_cards',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=50), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('card_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('reading_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('card_verified', sa.Boolean(), nullable=False),
    sa.Column('session_start', sa.DateTime(), nullable=False),
    sa.Column('session_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('reading_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_reading_sessions_user_end', ['user_id', 'session_end'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('book_title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('filed_by', sa.Integer(), nullable=True),
    sa.Column('date_filed', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_reports_filed', ['date_filed'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index('ix_reports_type', ['report_type'], unique=False)

    op.create_table('fines',
    sa.Column('fine_id', sa.Integer(), nullable=False),
    sa.Column('checkout_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('amount_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'issued', 'waived', 'paid', name='fine_status'), nullable=False),
    sa.Column('waiver_reason', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checkout_id'], ['checkouts.checkout_id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('fine_id'),
    sa.UniqueConstraint('checkout_id')
    )
    with op.batch_alter_table('fines', schema=None) as batch_op:
        batch_op.create_index('ix_fines_status', ['status'], unique=False)
        batch_op.create_index('ix_fines_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fines', schema=None) as batch_op:
        batch_op.drop_index('ix_fines_user_status')
        batch_op.drop_index('ix_fines_status')

    op.drop_table('fines')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_type')
        batch_op.drop_index(batch_op.f('ix_reports_report_type'))
        batch_op.drop_index('ix_reports_filed')

    op.drop_table('reports')
    with op.batch_alter_table('reading_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_reading_sessions_user_end')

    op.drop_table('reading_sessions')
    op.drop_table('library_cards')
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.drop_index('ix_checkouts_user_status')
        batch_op.drop_index('ix_checkouts_status_expected')
        batch_op.drop_index('ix_checkouts_book')

    op.drop_table('checkouts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_created')
        batch_op.drop_index('ix_audit_action_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_student_id'))
        batch_op.drop_index('ix_users_role_active')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('ix_users_approval_status')

    op.drop_table('users')
    op.drop_table('system_settings')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('ix_books_category_active')
        batch_op.drop_index(batch_op.f('ix_books_category'))
        batch_op.drop_index('ix_books_active')

    op.drop_table('books')
    # ### end Alembic commands ###
